%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.1

-ifndef(battle_pb).
-define(battle_pb, true).

-define(battle_pb_gpb_version, "4.0.1").

-ifndef('BATTLE_STAT_PB_H').
-define('BATTLE_STAT_PB_H', true).
-record(battle_stat,
        {
        }).
-endif.

-ifndef('BATTLE_END_NOTIFY_PB_H').
-define('BATTLE_END_NOTIFY_PB_H', true).
-record(battle_end_notify,
        {result                 :: non_neg_integer() | undefined, % = 1, 32 bits
         stat                   :: #battle_stat{} | undefined % = 2
        }).
-endif.

-ifndef('NAME_CARD_ST_PB_H').
-define('NAME_CARD_ST_PB_H', true).
-record(name_card_st,
        {name                   :: iolist() | undefined, % = 1
         last_set_time          :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('BATTLE_FRAME_PB_H').
-define('BATTLE_FRAME_PB_H', true).
-record(battle_frame,
        {
        }).
-endif.

-ifndef('BATTLE_FRAME_NOTIFY_PB_H').
-define('BATTLE_FRAME_NOTIFY_PB_H', true).
-record(battle_frame_notify,
        {sync_frame             :: non_neg_integer() | undefined, % = 1, 32 bits
         frames = []            :: [#battle_frame{}] | undefined % = 2
        }).
-endif.

-ifndef('TEAM_MEMBER_ST_PB_H').
-define('TEAM_MEMBER_ST_PB_H', true).
-record(team_member_st,
        {user_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         state                  :: 'inviting' | 'unready' | 'ready' | integer() | undefined, % = 2, enum team_member_state
         elf_id                 :: non_neg_integer() | undefined, % = 3, 32 bits
         name                   :: iolist() | undefined, % = 4
         level                  :: non_neg_integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('BATTLE_TEAM_MEMBER_PB_H').
-define('BATTLE_TEAM_MEMBER_PB_H', true).
-record(battle_team_member,
        {role_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         elf_id                 :: non_neg_integer() | undefined, % = 2, 32 bits
         name                   :: iolist() | undefined, % = 3
         level                  :: non_neg_integer() | undefined, % = 4, 32 bits
         team_id                :: non_neg_integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('BATTLE_TEAM_PB_H').
-define('BATTLE_TEAM_PB_H', true).
-record(battle_team,
        {members = []           :: [#battle_team_member{}] | undefined % = 1
        }).
-endif.

-ifndef('BATTLE_START_NOTIFY_PB_H').
-define('BATTLE_START_NOTIFY_PB_H', true).
-record(battle_start_notify,
        {battle_id              :: non_neg_integer() | undefined, % = 1, 32 bits
         battle_seed            :: non_neg_integer() | undefined, % = 2, 32 bits
         teams = []             :: [#battle_team{}] | undefined % = 3
        }).
-endif.

-ifndef('BATTLE_LOAD_PB_H').
-define('BATTLE_LOAD_PB_H', true).
-record(battle_load,
        {user_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         is_finished            :: boolean() | 0 | 1 | undefined, % = 2
         process                :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('BATTLE_END_PB_H').
-define('BATTLE_END_PB_H', true).
-record(battle_end,
        {user_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         result                 :: non_neg_integer() | undefined, % = 2, 32 bits
         stat                   :: #battle_stat{} | undefined % = 3
        }).
-endif.

-ifndef('BATTLE_FRAME_GROUP_PB_H').
-define('BATTLE_FRAME_GROUP_PB_H', true).
-record(battle_frame_group,
        {user_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         frames = []            :: [#battle_frame{}] | undefined % = 2
        }).
-endif.

-ifndef('BATTLE_START_PB_H').
-define('BATTLE_START_PB_H', true).
-record(battle_start,
        {user_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         confirm                :: boolean() | 0 | 1 | undefined % = 2
        }).
-endif.

-ifndef('BATTLE_UP_MSG_PB_H').
-define('BATTLE_UP_MSG_PB_H', true).
-record(battle_up_msg,
        {user_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         start                  :: #battle_start{} | undefined, % = 2
         load                   :: #battle_load{} | undefined, % = 3
         frame                  :: #battle_frame_group{} | undefined, % = 4
         eob                    :: #battle_end{} | undefined % = 5
        }).
-endif.

-ifndef('BATTLE_LOAD_NOTIFY_PB_H').
-define('BATTLE_LOAD_NOTIFY_PB_H', true).
-record(battle_load_notify,
        {loads = []             :: [#battle_load{}] | undefined % = 1
        }).
-endif.

-ifndef('BATTLE_NOTIFY_MSG_PB_H').
-define('BATTLE_NOTIFY_MSG_PB_H', true).
-record(battle_notify_msg,
        {sob                    :: #battle_start_notify{} | undefined, % = 1
         load                   :: #battle_load_notify{} | undefined, % = 2
         frame                  :: #battle_frame_notify{} | undefined, % = 3
         eob                    :: #battle_end_notify{} | undefined % = 4
        }).
-endif.

-ifndef('ROLE_ST_PB_H').
-define('ROLE_ST_PB_H', true).
-record(role_st,
        {role_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         elf_id                 :: non_neg_integer() | undefined, % = 2, 32 bits
         name_card              :: #name_card_st{} | undefined, % = 3
         level                  :: non_neg_integer() | undefined, % = 4, 32 bits
         exp                    :: non_neg_integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('ROLE_SUMMARY_ST_PB_H').
-define('ROLE_SUMMARY_ST_PB_H', true).
-record(role_summary_st,
        {role_id                :: non_neg_integer() | undefined, % = 1, 32 bits
         elf_id                 :: non_neg_integer() | undefined, % = 2, 32 bits
         name                   :: iolist() | undefined, % = 3
         level                  :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('TEAM_INFO_ST_PB_H').
-define('TEAM_INFO_ST_PB_H', true).
-record(team_info_st,
        {members = []           :: [#team_member_st{}] | undefined, % = 1
         leader_id              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
